title: Chunlin Gong's Homepage
page-top-title: Chunlin Gong
top-section-bg-text: Computer Science
home-subtitle: Chunlin Gong&ensp;|&ensp;Cheslyn
copyright-text: 'Chunlin Gong personal academic website.'
